name: Yaspeller

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  speller-yandex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Проверка орфографии с помощью Yaspeller
        run: npx yaspeller *.html
